project: living-bio
application: fsvid2vid
port: 80

resources:
  requests:
    cpu: 1
    memory: 6Gi
  limits:
    cpu: 2
    memory: 8Gi

automatic_scaling:
  min: 0
  max: 1

node:
  scope: gpu

env_variables:
#  SETTINGS: "app.conf.Base"
  CLOUDINARY_CLOUD_NAME: %CLOUDINARY_CLOUD_NAME%
  CLOUDINARY_API_KEY: %CLOUDINARY_API_KEY%
  CLOUDINARY_API_SECRET: %CLOUDINARY_API_SECRET%

cmd: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]